apiToken: 1654138997:AAGn6RGea9oU6brfwUCcUvXrQJZRqnJVIOs # replace by your own
chatId: -1001331374604 # replace by your own
eventFilePath: event.yaml # info about current event is stored in this file
maxParticipants: 0 # set to zero for unlimited participants

scheduleCommand: Создать встречу
editCommand: Иземнить встречу
goCommand: Вступить во встречу
quitCommand: Выйти из встречи
cancelCommand: Отменить встречу

waitlistedHeader: Wait list

scheduledMessage: Встреча создана!
cancelledMessage: Встреча отменена!
editedMessage: Встреча отредактирована!
notAdminMessage: Вы не админ!
noEventScheduledMessage: Встреча не назначена!
noEventDescriptionMessage: Пожалуйста, опишите встречу!
alreadyInEventMessage: Уже во встрече!
notInEventMessage: Еще не во встрече!
